posts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



app_name = 'posts'
urlpatterns = [
    path('', views.post_list, name = 'list'),
    path('create_post/', views.post_create, name = "create"),
    path('post_detail/<id>/', views.post_detail, name = 'detail'),
    path('my_post', views.my_post, name = 'myPost'),
    path('search_bar/', views.search_bar, name = 'searchBar'),
    path('post_update/<id>/', views.post_update, name = 'update'),
    path('post_delete/<id>/', views.post_delete, name = 'remove'),
    path('post_filter', views.post_filters, name = 'filters'),
    path('contact.html', views.contact, name = "contact"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

rentahome/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from posts import views as post_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', views.about),
    path('', post_views.post_list, name = 'home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.contrib.auth.models import User


# Creating a post
class Post(models.Model):
    place = models.CharField(max_length = 40)
    address = models.CharField(max_length = 100)
    rent = models.PositiveIntegerField()
    bedroom = models.PositiveSmallIntegerField()
    bathroom = models.PositiveSmallIntegerField()
    size = models.PositiveIntegerField()
    phone = models.PositiveIntegerField() 
    owner= models.ForeignKey(User,on_delete=models.CASCADE, default = None)
    date_posted = models.DateTimeField(auto_now_add = True,)
    image = models.ImageField(default = 'default.jpg', upload_to = 'house_pics')
    likes = models.ManyToManyField(User, related_name = 'advertisement_post')

    def __str__(self):
        return self.place





posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['place','address','rent','bedroom','bathroom','size','phone','image']

posts/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms
from django.core.mail import send_mail


# Function for showing Post lists
def post_list(request):
    posts = Post.objects.all().order_by('date_posted')
    return render(request, 'posts/post_list.html', {'posts': posts})

# Function for creating posts
@login_required(login_url = "/accounts/login/")
def post_create(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            # save post to database
            instance = form.save(commit = False)
            instance.owner = request.user
            instance.save()
            return redirect('posts:list')
    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_create.html', {'form': form})

# Function for showing details of any particular post
@login_required(login_url = "/accounts/login/")
def post_detail(request,id):
    post = Post.objects.get(id=id)
    return render(request,'posts/post_detail.html', {'post': post})


# Function for showing users' own advertisements        
def my_post(request):
    post = Post.objects.all()
    return render (request, 'posts/my_post.html',{'post': post})


# Function for searching
def search_bar(request):
    if request.method == "POST":
        searched = request.POST['searched']
        post = Post.objects.filter(place__contains = searched)
        return render (request, 'posts/search_bar.html',{'searched': searched, 'post': post})

# Function for updating a particular post
def post_update(request,id):
    post = Post.objects.get(id=id)
    form = forms.CreatePost(request.POST or None, request.FILES or None, instance = post)
    if form.is_valid():
        form.save()
        return redirect('posts:detail', post.id)
    return render(request,'posts/post_update.html', {'post': post, 'form': form})

# Function to delete a post
def post_delete(request,id):
    post = Post.objects.get(id=id)
    if request.method == "POST":
        post.delete()
        return redirect('posts:myPost')
    return render(request, 'posts/post_delete.html',{'post': post})

# Funtion to filter posts by Budget
def post_filters(request):

    query = request.GET['query']
    if query == "0":
        post = Post.objects.filter(rent__gte = 0)
        return render(request, 'posts/filter.html',{'post': post})
    elif query == "1":
        post = Post.objects.filter(rent__lt = 15000)
        return render(request, 'posts/filter.html',{'post': post})
    elif query == "2":
        post = Post.objects.filter(rent__range = (15000,20000))
        return render(request, 'posts/filter.html', {'post': post})
    elif query == "3":
        post = Post.objects.filter(rent__range = (20001,25000))
        return render(request, 'posts/filter.html', {'post': post})
    elif query == "4":
        post = Post.objects.filter(rent__range = (25001,30000))
        return render(request, 'posts/filter.html', {'post': post})
    elif query == "5":
        post = Post.objects.filter(rent__range = (30001,40000))
        return render(request, 'posts/filter.html', {'post': post})
    elif query == "6":
        post = Post.objects.filter(rent__range = (40001,50000))
        return render(request, 'posts/filter.html', {'post': post})
    elif query == "7":
        post = Post.objects.filter(rent__gt = 50000)
        return render(request, 'posts/filter.html', {'post': post})
        
def contact(request):
    if request.method == "POST":
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message = request.POST['message']
        # Sending a mail
        send_mail(
            message_name,
            message,
            message_email,
            ['sumiya.sadia@northsouth.edu', 'ezaz.ahamed@northsouth.edu', 'sumiya.sadia97@gmail.com', 'turkidot@gmail.com'] # Email addresses
        )
        return render(request, 'posts/contact.html', {'post': message_name, 'message_email': message_email, 'message': message})
    else:
        return render(request, 'posts/contact.html', {})

posts/templates/posts/contact.html
{% extends 'base.html' %}

{% block content %}
<h1>Enter your Complaints/Thoughts</h1>
<form action = "{% url 'posts:contact' %}" method = "post">
    {% csrf_token %}
    <div>
        <input type = "text" name = "message-name" placeholder = "your name">
    </div>
    <div>
        <input type = "email" name = "message-email" placeholder = "your email">
    </div>
    <div>
        <textarea name = "message" placeholder = "your message"></textarea>
    </div>
    <div>
        <button type = "submit"><i class = "fa fa-envelope"></i>Send</button>
    </div>
    
</form>
  
{% endblock %}

posts/templates/posts/filter.html
{% extends 'base.html' %}

{% block content %}
<div class = "posts">
    {% for post in Post %}
    <a class = "search-results" href = "{% url 'posts:detail' post.id %}">{{ post }}</a><br/>
    {% endfor %}
</div>
  
{% endblock%}

posts/templates/posts/my_post.html
{% extends 'base.html' %}

{% block content %}

<h1> Your Advertisements</h1>
<div class = "posts">
  {% for post in post %}
    {% if post.owner == user %} 
    <div class = "post"> 
      <h2><a href = "{% url 'posts:detail' id=post.id %}">{{post.place}}</a></h2>
      <h2>Address: {{post.address}}.</h2>
      <h2>Rent Price: BDT {{post.rent}}.</h2>
      <h2>Number of Bedrooms: {{post.bedroom}}.</h2>
      <h2>Number of Bathrooms: {{post.bathroom}}.</h2>
      <h2>Flat Size in sqft: {{post.size}} sqft.</h2>
      <h2>Owner's Name: {{post.owner}}.</h2>
      <p>Posted on: {{post.date_posted}}</p>
      <p><a href = "{% url 'posts:detail' id=post.id %}">Click to view more details</a></p>
      <div class = "edit-buttons">
        <p><a class = "highlight" href = "{% url 'n 
</div> 

{% endblock %},,,,,,,,,.l m.l,l.,

posts/templates/posts/post_create.html
{% extends 'base.html' %}

{% block content %}
<div class = "create-post">
    <h1>Create a New Post</h1>
    <form class = "site-form" action = "{% url 'posts:create' %}" method = "post" enctype = "multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type = "submit" value = "Create">
    </form>
</div>
{% endblock %}

posts/templates/posts/post_delete.html
{% extends 'base.html' %}

{% block content %}
<div class = "delete-sure">
    <center>
        <h1>Are you sure you want to delete this post?</h1>
        
        <form action = "{% url 'posts:remove' post.id %}" method = "post">
            {% csrf_token %}
            
            <input class = "delete" type = "submit" value = "Delete">
            <a class = "highlight" href = "{% url 'posts:detail' post.id %}">Cancel</a>
        </form>
        </center>
</div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content %}
<center>
<div class = "post-detail">
    <div class = "post">
        <h1>Location: {{post.place}}</a></h1><br>
        <img src = "{{ post.image.url }}" alt = "House picture/None" width = "600" height = "600"><br>
        <h2>Address: {{post.address}}.</h2><br>
        <h2>Rent Price: BDT {{post.rent}}.</h2><br>
        <h2>Number of Bedrooms: {{post.bedroom}}.</h2><br>
        <h2>Number of Bathrooms: {{post.bathroom}}.</h2><br>
        <h2>Flat Size in sqft: {{post.size}} sqft.</h2><br>
        <h2>Owner's Name: {{post.owner}}.</h2><br>
        <h2>Owner's Contact Number: +880{{post.phone}}.</h2><br>
        <p>Posted on: {{post.date_posted}}</p><br> 
        {% if post.owner == user %} 
        <p><a class = "highlight" href = "{% url 'posts:update' post.id %}">Update</a>  
        <a class = "delete" href = "{% url 'posts:remove' post.id %}">Delete</a></p>
        {% endif %}
    </div>
</div>
</center>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Properties for rent/sale in Bangladesh</h1>
    <div class = "posts">
        {% for post in posts %}
        <div class = "post">
            <h1><a href = "{% url 'posts:detail' post.id %}">{{post.place}}</a></h1>
            <div class = "post-card">
                <ul>
                    <li><h2>Address: {{post.address}}.</h2></li>
                    <li><h2>Rent Price: BDT {{post.rent}}.</h2></li>
                    <li><h2>Number of Bedrooms: {{post.bedroom}}.</h2></li>
                    <li><h2>Number of Bathrooms: {{post.bathroom}}.</h2></li>
                    <li><h2>Flat Size in sqft: {{post.size}} sqft.</h2></li>
                </ul>
            </div>
            <br>
                <center>
                    <p>Posted on: {{post.date_posted}}</p>
                    <p><a href = "{% url 'posts:detail' post.id %}">Click to view more details</a></p>
                </center>
        </div>
        {% endfor %}
    </div>
{% endblock %}

posts/templates/posts/post_update.html
{% extends 'base.html' %}

{% block content %}

<div>
    <h1>Update Post</h1>
    <form action = "{% url 'posts:update' post.id %}" class = "site-form" method = "post" enctype = "multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type = "submit" class = "update-button" value = "Save"><br>
        <a href = "{% url 'posts:detail' post.id %}" class = "highlight">Cancel</a>
    </form>           
</div>

{% endblock %}

posts/templates/posts/search_bar.html
{% extends 'base.html' %}

{% block content %}
    {% if searched %}
         <h1>You Searched for "{{ searched }}"</h1>
         <br/>
        {% for post in post %}
        <div class = "search-results-wrapper">
            <a class = "search-results" href = "{% url 'posts:detail' post.id %}">{{ post }}</a><br/>
        </div>
        {% endfor %}
    {% else %}
        <h1>You Didn't Search for Anything!</h1>
    {% endif %}
{% endblock %}